apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-dispatcher
spec:
  selector:
    matchLabels:
      app: notification-dispatcher
  replicas: 1
  template:
    metadata:
      labels:
        app: notification-dispatcher
    spec:
      containers:
        - name: notification-dispatcher
          image: ekaegor/notification-dispatcher:v3 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 
