apiVersion: v1
kind: Service
metadata:
  name: notification-dispather
spec:
  selector:
    app: notification-dispatcher
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8080
  type: NodePort
