/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.notification.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Transport extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2761367904502736058L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Transport\",\"namespace\":\"com.example.notification.schema\",\"fields\":[{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"endpoint\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Transport> ENCODER =
      new BinaryMessageEncoder<Transport>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Transport> DECODER =
      new BinaryMessageDecoder<Transport>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Transport> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Transport> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Transport>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Transport to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Transport from a ByteBuffer. */
  public static Transport fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence type;
  @Deprecated public java.lang.CharSequence endpoint;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Transport() {}

  /**
   * All-args constructor.
   * @param type The new value for type
   * @param endpoint The new value for endpoint
   */
  public Transport(java.lang.CharSequence type, java.lang.CharSequence endpoint) {
    this.type = type;
    this.endpoint = endpoint;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return type;
    case 1: return endpoint;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: type = (java.lang.CharSequence)value$; break;
    case 1: endpoint = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'endpoint' field.
   * @return The value of the 'endpoint' field.
   */
  public java.lang.CharSequence getEndpoint() {
    return endpoint;
  }

  /**
   * Sets the value of the 'endpoint' field.
   * @param value the value to set.
   */
  public void setEndpoint(java.lang.CharSequence value) {
    this.endpoint = value;
  }

  /**
   * Creates a new Transport RecordBuilder.
   * @return A new Transport RecordBuilder
   */
  public static Transport.Builder newBuilder() {
    return new Transport.Builder();
  }

  /**
   * Creates a new Transport RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Transport RecordBuilder
   */
  public static Transport.Builder newBuilder(Transport.Builder other) {
    return new Transport.Builder(other);
  }

  /**
   * Creates a new Transport RecordBuilder by copying an existing Transport instance.
   * @param other The existing instance to copy.
   * @return A new Transport RecordBuilder
   */
  public static Transport.Builder newBuilder(Transport other) {
    return new Transport.Builder(other);
  }

  /**
   * RecordBuilder for Transport instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Transport>
    implements org.apache.avro.data.RecordBuilder<Transport> {

    private java.lang.CharSequence type;
    private java.lang.CharSequence endpoint;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Transport.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.endpoint)) {
        this.endpoint = data().deepCopy(fields()[1].schema(), other.endpoint);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Transport instance
     * @param other The existing instance to copy.
     */
    private Builder(Transport other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.endpoint)) {
        this.endpoint = data().deepCopy(fields()[1].schema(), other.endpoint);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }

    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public Transport.Builder setType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public Transport.Builder clearType() {
      type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'endpoint' field.
      * @return The value.
      */
    public java.lang.CharSequence getEndpoint() {
      return endpoint;
    }

    /**
      * Sets the value of the 'endpoint' field.
      * @param value The value of 'endpoint'.
      * @return This builder.
      */
    public Transport.Builder setEndpoint(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.endpoint = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'endpoint' field has been set.
      * @return True if the 'endpoint' field has been set, false otherwise.
      */
    public boolean hasEndpoint() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'endpoint' field.
      * @return This builder.
      */
    public Transport.Builder clearEndpoint() {
      endpoint = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Transport build() {
      try {
        Transport record = new Transport();
        record.type = fieldSetFlags()[0] ? this.type : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.endpoint = fieldSetFlags()[1] ? this.endpoint : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Transport>
    WRITER$ = (org.apache.avro.io.DatumWriter<Transport>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Transport>
    READER$ = (org.apache.avro.io.DatumReader<Transport>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
